TradeExecutor.cpp:
  - bool TradeExecutor::HandleActionSignal(action, price, amount)
  - void TradeExecutor::DisplayPortfolioStatus(currentPrice)
  
TradingStrategy.cpp:
   - ActionType TradingStrategy::CalculateSimpleMovingAverageStrategy(priceHistory)
